kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: mysql
    project: expense
  ports: 
  - protocol: TCP
    port: 3306
    targetPort: 3306